spring.application.name=itau-backend

# Management endpoints configuration
management.endpoints.web.exposure.include=health,info,metrics,swagger-ui
management.endpoint.health.show-details=always
management.info.env.enable=true
management.info.app.name=Transaction API
management.info.app.version=1.0.0
management.info.app.description=API for managing transactions
management.info.metrics.tags.application=api-transactions
management.metrics.enable.all=true

# SpringDoc configuration
springdoc.show-actuator=true